[package]
name = "qpp-ascon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rand_core = { workspace = true }
ascon-aead128 = { workspace = true }

[dev-dependencies]
qpp-rng-reference = { workspace = true }